project_id = "osqreiyssdhpplxtcxdv"

[functions.register-device-token]
verify_jwt = false

[functions.twilio-sms]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.push-debug]
verify_jwt = false
